name: syntinel-dashboard
services:
  syntinel-dashboard:
    container_name: syntinel-dashboard
    image: syntinel-dashboard:latest
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=
    restart: always
